[tool.isort]
profile = "black"
multi_line_output = 3
py_version = 37
line_length = 100
known_unrealsdk = "unrealsdk"
known_modmenu = "Mods.ModMenu"
sections = [
    "FUTURE",
    "UNREALSDK",
    "STDLIB",
    "THIRDPARTY",
    "MODMENU",
    "FIRSTPARTY",
    "LOCALFOLDER",
]
no_lines_before = ["STDLIB", "FIRSTPARTY"]

[tool.black]
exclude = "dist"
line-length = 100
target-version = ['py37']
